// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBmEfeX502nyy5hZnfEbOw8pp1BINrfc',
    appId: '1:986489785639:web:4d62aa5c58bc17ffcfad02',
    messagingSenderId: '986489785639',
    projectId: 'brew-crew-test-c15b5',
    authDomain: 'brew-crew-test-c15b5.firebaseapp.com',
    storageBucket: 'brew-crew-test-c15b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1iFFaxJP_kD4QtVZvcwCr2sUDdVpBDlw',
    appId: '1:986489785639:android:4567b3c7b19bb458cfad02',
    messagingSenderId: '986489785639',
    projectId: 'brew-crew-test-c15b5',
    storageBucket: 'brew-crew-test-c15b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCc51NBeNHICafKna7HA1DgOesTW4tCw',
    appId: '1:986489785639:ios:1a883cf45a7c0990cfad02',
    messagingSenderId: '986489785639',
    projectId: 'brew-crew-test-c15b5',
    storageBucket: 'brew-crew-test-c15b5.appspot.com',
    iosBundleId: 'com.example.coffeeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCc51NBeNHICafKna7HA1DgOesTW4tCw',
    appId: '1:986489785639:ios:89c22247525ff028cfad02',
    messagingSenderId: '986489785639',
    projectId: 'brew-crew-test-c15b5',
    storageBucket: 'brew-crew-test-c15b5.appspot.com',
    iosBundleId: 'com.example.coffeeFirebase.RunnerTests',
  );
}
